services:
  php:
    env_file:
      - "../../.env"
    image: wsb_php_classic
    container_name: php-apache
    restart: "no"
    volumes:
      - "../classic/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../classic/apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "../classic/apache2/ports.conf:/etc/apache2/ports.conf"
      - "../classic/apache2/apache2.conf:/etc/apache2/apache2.conf"
      - ${APP_LOG_PATH}/apache:/var/log/apache2
      - ${APP_LOG_PATH}/php:/var/log/php
      - ../../${APP_PATH}:/var/www
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
        reservations:
          cpus: '1'
          memory: 1024M
    ports:
      - "8090:8090"
      - "8091:8091"
    links:
      - db:db
    networks:
      wsbclassic:
        ipv4_address: 172.28.0.1

  db:
    env_file:
      - "../../.env"
    image: wsb_db
    container_name: mariadb
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASS}
    restart: "no"
    volumes:
      - "../classic/db/my.cnf:/etc/mysql/my.cnf"
      - "../classic/db/my-conf.d/zbx-custom.cnf:/etc/mysql/my-conf.d/zbx-custom.cnf"
      - ${APP_LOG_PATH}/db:/var/log/mysql
      - ${APP_CACHE_PATH}/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      wsbclassic:
        ipv4_address: 172.28.0.3

  phpmyadmin:
    env_file:
      - "../../.env"
    image: wsb_pma_classic
    container_name: phpmyadmin
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    volumes:
      - ${APP_LOG_PATH}/pma/apache2:/var/log/apache2
    links:
      - db:db
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      wsbclassic:
        ipv4_address: 172.28.0.4

  nginx:
    env_file:
      - "../../.env"
    image: wsb_nginx_classic
    container_name: nginx
    restart: "no"
    volumes:
      - "../classic/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "../classic/nginx/sites-available/default.conf:/etc/nginx/sites-available/default.conf"
      - "../classic/nginx/sites-available/rtc.conf:/etc/nginx/sites-available/rtc.conf"
      - ${APP_LOG_PATH}/nginx:/var/log/nginx
      - ../../${APP_PATH}:/var/www
    ports:
      - "80:80"
      - "81:81"
    networks:
      wsbclassic:
        ipv4_address: 172.28.0.2
    extra_hosts:
      - "php-apache:172.28.0.1"
    depends_on:
      - php
      - db

  redis:
    env_file:
      - "../../.env"
    image: wsb_redis
    container_name: redis
    privileged: true
    restart: "no"
    volumes:
      - ${APP_CACHE_PATH}/redis:/data
      - "../classic/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - ${APP_LOG_PATH}/redis:/var/log/redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    ports:
      - "6379:6379"
    networks:
      wsbclassic:
        ipv4_address: 172.28.0.6
    depends_on:
      - nginx

networks:
  wsbclassic:
    name: "wsb_intranet_classic"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254